name: Publish Components

on:
  workflow_dispatch:
    inputs:
      component:
        required: true
        type: string
      message:
        type: string
        default: Release ${{ github.event.repository.updated_at }}
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - run: npm install bit-bin --global

      - run: bit status
      - run: bit tag ${{ inputs.component }} -m ${{ inputs.message }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
